name: Deploy to Server

on:
  push:
    branches:
    - main #trigger deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkouts@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect to Server and update repo + run artisan
      run: |
        ssh -o StrictHostKeyChecking=no sinprobau_admin@4.228.229.11:22 << 'EOF'
          cd /var/www/SinProBau_2025_01 || exit
          git pull origin main || exit
          composer install --no-dev --optimize-autoloader || exit
          php artisan migrate --force || exit
          php artisan config:clear || exit
          php artisan cache:clear || exit
          php artisan optimize || exit
          echo "Deployment successfull"
        EOF
